### ISSUE TITLE
ptrs style

### ISSUE THREAD

**Issue by IvanJasenov** [cs50/lib50-c#38]
Something caught my in the code and that is the coding style of the pointers, not the way it's done in the lectures, the way I used to learn them like for example `int* n`, instead the more "old school" style `int *n`. Don't get me wrong guys, both are correct but this just does not correlates  with the lecture style.
If change needed, just give me a green light.

**Comment by dmalan** [comment]
We've reverted to the more typical

`int *n`

this year!
