### ISSUE TITLE
getprogname() missing on Windows(MinGW)

### ISSUE THREAD

**Issue by Bintel** [cs50/lib50-c#39]
I use Windows 10 and MinGW-w64, gcc version is 6.1.0

gcc(MinGW-w64) shows:
```
error: implicit declaration of function 'getprogname' [-Werror=implicit-function-declaration]
#define program_invocation_short_name getprogname()
                                      ^
```

I couldn't fine the definition `program_invocation_short_name` or `getprogname()` in both `stdlib.h` and `errno.h`. Are there any alternative solutions?

**Comment by FreeER** [comment]
getprogname appears to only be available on some *nix systems (not really sure what subset)... Though I did find this as well, not certain if that will help or not

https://lists.gnu.org/archive/html/bug-gnulib/2010-12/txtrjMzutB7Em.txt

It does mention mingw (as well as cygwin)

**Comment by Bintel** [comment]
Hi, @FreeER 

Thanks for your help. It seems that they use `GetModuleFileName`(on `windows.h`) to achieve it on windows.

Hope @dmalan or another contributor can provide a more generic way to solve this problem.

Sincerely thanks to all those who have contributed to this project.

**Comment by dmalan** [comment]
@Bintel, we're going to remove (as not all that enlightening) the program's name from `eprintf`'s output in the next version, so this problem will disappear!

**Comment by dmalan** [comment]
https://github.com/cs50/lib50-c/pull/51
