### ISSUE TITLE
Why use get_* and Get* but not use Get* directly?

### ISSUE THREAD

**Issue by Bintel** [cs50/lib50-c#43]
I don't know why, can you tell me?

**Comment by kzidane** [comment]
`Get*` functions are to be deprecated starting January. `get_*` replace them, as [snake case](https://en.wikipedia.org/wiki/Snake_case) is more typically used for naming functions in C, if that's what you're asking.

**Comment by Bintel** [comment]
Hello, @kzidane 
Thanks for your answer, so `get_*` replace `Get*` only just a style change, keep `Get*` just for compatibility? Is my understanding correct?
(Please excuse my poor English...)

**Comment by kzidane** [comment]
Yes.

**Comment by Bintel** [comment]
@kzidane Thanks for your help again!
